# Generated by Django 4.2.14 on 2024-08-04 02:06

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=70)),
                ('dni_o_pasaporte', models.CharField(max_length=15)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('notas_personas', models.TextField(blank=True, max_length=500)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupantes', to='habitaciones.habitacion')),
            ],
        ),
    ]
