# Generated by Django 4.2.14 on 2024-08-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ha_ingresado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='ha_salido',
            field=models.BooleanField(default=False),
        ),
    ]
