# Generated by Django 4.2.14 on 2024-08-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
