# Generated by Django 5.0.7 on 2024-07-25 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10)),
                ('libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni_o_pasaporte', models.CharField(max_length=50)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrado', models.BooleanField(default=False)),
                ('salio', models.BooleanField(default=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('numero_habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registroPersonas.habitacion')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='habitaciones', to='registroPersonas.persona'),
        ),
    ]
