# Generated by Django 5.0.7 on 2024-07-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='personas',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='datos_personas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroPersonas.habitacion'),
        ),
    ]
