# Generated by Django 5.0.7 on 2024-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0004_persona_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
