# Generated by Django 5.0.7 on 2024-07-25 16:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0005_persona_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
