# Generated by Django 5.0.7 on 2024-07-25 17:35

import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0006_alter_persona_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario_responsable',
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni_o_pasaporte',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
