# Generated by Django 5.0.7 on 2024-07-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0008_persona_usuario_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
