# Generated by Django 5.0.7 on 2024-07-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroPersonas', '0010_personaborrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonaBorrada',
        ),
    ]
